### ISSUE TITLE
Not really an issue..

### ISSUE THREAD

**Issue by sureshk75** [pijarr/pijarr#12]
I really appreciate the effort you put into this script. It has allowed me to turn my RPI4 into an amazing home entertainment system. Just out of curiosity, are there plans to include Bazarr and Sonarr v4 in the coming future?
Regardless, thanks for the script!

**Comment by baloo2** [comment]
I also vote for including Bazarr.

**Comment by pijarr** [comment]
Added support for Bazarr. Haven't done extensive testing, just on Debian 11/12. See how it goes.
