### ISSUE TITLE
Don't have write permission

### ISSUE THREAD

**Issue by Creefears** [pijarr/pijarr#15]
Hi, 

Thanks for this wonderful script, a easy way for a noob like me to install my favorite automation software.
But I have a major issue, not with your script but with the sonarr/radarr's configuration, I can't choose a root folder or a folder for my show. Visibly I don't have the write permission to create forlder in my mount disk or anywhere else.

I think I just do something bad in the process so maybe you can help me with that

Thanks !!

**Comment by pijarr** [comment]
I couldn't replicate the issue however I added some permission changes in latest script like adding current user to app group.
