### ISSUE TITLE
sonarr v4

### ISSUE THREAD

**Issue by rigas40** [pijarr/pijarr#18]
not work because use mono exe

**Comment by mrpainte** [comment]
i just tried to update this by changing line 175 to:
`sonarr_src_url="https://services.sonarr.tv/v1/download/main/latest?version=4&os=linux"`
and line 378 to:
`          app_exec="${app_opt_path}/$(title_case ${app_name}) -nobrowser"`

however `systemctl status sonarr`
just shows that its "starting sonarr daemon" but when i try to run it manually 
`sudo su
./opt/Sonarr/Sonarr --nobrowser`
i just get  
`bash: ./Sonarr: cannot execute binary file: Exec format error`

PS running on raspberry pi 4 8gb

**Comment by pijarr** [comment]
Updated script to support now support Sonarr v4, just download and run latest version of script.
