### ISSUE TITLE
setup failed!?!

### ISSUE THREAD

**Issue by mrgravy20** [pijarr/pijarr#7]
i ran all 3 ways you provided and the following is the output. I have a pi 4 8gb, and am running the latest pi OS... the old script still works fine

                                                                      
▓▓▓▓▓▓▓▓▓▓▓▓▓ ▓▓▓▓          ▓▓▓▓ ▓▓▓▓▓▓▓▓▓▓▓▓▓ ▓▓▓▓▓▓▓▓▓▓▓▓▓ ▓▓▓▓▓▓▓▓▓▓▓▓▓
▓▓▓▓     ▓▓▓▓               ▓▓▓▓ ▓▓▓▓     ▓▓▓▓ ▓▓▓▓     ▓▓▓▓ ▓▓▓▓     ▓▓▓▓
▓▓▓▓▓▓▓▓▓▓▓▓▓ ▓▓▓▓ ▓▓▓▓     ▓▓▓▓ ▓▓▓▓▓▓▓▓▓▓▓▓▓ ▓▓▓▓▓▓▓▓▓▓▓▓▓ ▓▓▓▓▓▓▓▓▓▓▓▓▓
▓▓▓▓          ▓▓▓▓ ▓▓▓▓     ▓▓▓▓ ▓▓▓▓     ▓▓▓▓ ▓▓▓▓   ▓▓▓▓   ▓▓▓▓   ▓▓▓▓
▓▓▓▓          ▓▓▓▓ ▓▓▓▓▓▓▓▓▓▓▓▓▓ ▓▓▓▓     ▓▓▓▓ ▓▓▓▓    ▓▓▓▓▓ ▓▓▓▓    ▓▓▓▓▓

Name:           pijarr/setup.sh
Description:    Raspberry Pi installer for Jackett, Sonarr, Radarr, and Lidarr
Author:         github.com/pijarr
Tested:         Raspberry Pi 3 & 4 running Raspbian Buster

Notes:          Requiries sudo/root superuser permissions to run.

                If they are not already installed the required dependencies including 
                Mono (Cross platform, open source .NET framework) may take a while to 
                download and install. 
                
                After initial setup the web interface for the application may need a short time 
                to start before being available on the nominated host port.

Do you wish to continue (y/N)? Y

Updating packages using apt update...
Get:1 http://raspbian.raspberrypi.org/raspbian bullseye InRelease [15.0 kB]
Get:2 http://archive.raspberrypi.org/debian bullseye InRelease [23.5 kB]
Get:3 http://archive.raspberrypi.org/debian bullseye/main armhf Packages [247 kB]
Fetched 286 kB in 1s (203 kB/s)   
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
6 packages can be upgraded. Run 'apt list --upgradable' to see them.
Upgrading packages using apt upgrade...
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following package was automatically installed and is no longer required:
  libfuse2
Use 'sudo apt autoremove' to remove it.
The following packages will be upgraded:
  firmware-atheros firmware-brcm80211 firmware-libertas firmware-misc-nonfree
  firmware-realtek rpd-plym-splash
6 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 43.4 MB of archives.
After this operation, 2,048 B of additional disk space will be used.
Get:1 http://archive.raspberrypi.org/debian bullseye/main armhf firmware-atheros all 1:20210315-3+rpt5 [10.0 MB]
Get:2 http://archive.raspberrypi.org/debian bullseye/main armhf firmware-brcm80211 all 1:20210315-3+rpt5 [5,787 kB]
Get:3 http://archive.raspberrypi.org/debian bullseye/main armhf firmware-libertas all 1:20210315-3+rpt5 [17.7 MB]
Get:4 http://archive.raspberrypi.org/debian bullseye/main armhf firmware-misc-nonfree all 1:20210315-3+rpt5 [8,953 kB]
Get:5 http://archive.raspberrypi.org/debian bullseye/main armhf firmware-realtek all 1:20210315-3+rpt5 [922 kB]
Get:6 http://archive.raspberrypi.org/debian bullseye/main armhf rpd-plym-splash armhf 0.30 [34.9 kB]
Fetched 43.4 MB in 1min 13s (592 kB/s)                                         
apt-listchanges: Reading changelogs...
(Reading database ... 99974 files and directories currently installed.)
Preparing to unpack .../0-firmware-atheros_1%3a20210315-3+rpt5_all.deb ...
Unpacking firmware-atheros (1:20210315-3+rpt5) over (1:20210315-3+rpt4) ...
Preparing to unpack .../1-firmware-brcm80211_1%3a20210315-3+rpt5_all.deb ...
Unpacking firmware-brcm80211 (1:20210315-3+rpt5) over (1:20210315-3+rpt4) ...
Preparing to unpack .../2-firmware-libertas_1%3a20210315-3+rpt5_all.deb ...
Unpacking firmware-libertas (1:20210315-3+rpt5) over (1:20210315-3+rpt4) ...
Preparing to unpack .../3-firmware-misc-nonfree_1%3a20210315-3+rpt5_all.deb ...
Unpacking firmware-misc-nonfree (1:20210315-3+rpt5) over (1:20210315-3+rpt4) ...
Preparing to unpack .../4-firmware-realtek_1%3a20210315-3+rpt5_all.deb ...
Unpacking firmware-realtek (1:20210315-3+rpt5) over (1:20210315-3+rpt4) ...
Preparing to unpack .../5-rpd-plym-splash_0.30_armhf.deb ...
Unpacking rpd-plym-splash (0.30) over (0.29) ...
Setting up rpd-plym-splash (0.30) ...
update-initramfs: deferring update (trigger activated)
Setting up firmware-atheros (1:20210315-3+rpt5) ...
Setting up firmware-misc-nonfree (1:20210315-3+rpt5) ...
Setting up firmware-brcm80211 (1:20210315-3+rpt5) ...
Setting up firmware-realtek (1:20210315-3+rpt5) ...
Setting up firmware-libertas (1:20210315-3+rpt5) ...
Processing triggers for initramfs-tools (0.140) ...
Running package clean-up using apt autoclean and autoremove...
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages will be REMOVED:
  libfuse2
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 288 kB disk space will be freed.
(Reading database ... 99974 files and directories currently installed.)
Removing libfuse2:armhf (2.9.9-5) ...
Processing triggers for libc-bin (2.31-13+rpt2+rpi1+deb11u2) ...
Setup Dependencies
Installing required dependencies...
[✘] Package apt-transport-https not found.
Attempting to install apt-transport-https package with apt...
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  apt-transport-https
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 160 kB of archives.
After this operation, 166 kB of additional disk space will be used.
Get:1 http://mirror.umd.edu/raspbian/raspbian bullseye/main armhf apt-transport-https all 2.2.4 [160 kB]
Fetched 160 kB in 0s (412 kB/s)             
Selecting previously unselected package apt-transport-https.
(Reading database ... 99961 files and directories currently installed.)
Preparing to unpack .../apt-transport-https_2.2.4_all.deb ...
Unpacking apt-transport-https (2.2.4) ...
Setting up apt-transport-https (2.2.4) ...
Package apt-transport-https is now installed.
[✔] Checking for required package > dirmngr
[✔] Checking for required package > gnupg
[✔] Checking for required package > ca-certificates
Adding repository key and apt source for mono...
pi@Pi-Hole:~ $

**Comment by pijarr** [comment]
Found it was an error with gpg directory permissions:
gpg: failed to create temporary file '/root/.gnupg/.#lk0x00a93d50.raspberrypi.2563': No such file or directory
gpg: connecting dirmngr at '/root/.gnupg/S.dirmngr' failed: No such file or directory
gpg: keyserver receive failed: No dirmngr

A manual fix is to run the `sudo gpg` command once own then ctrl-c and this will create required directories and permissions.

Fixes added to script -
sudo mkdir -p /root/.gnupg
sudo chmod -R 600 /root/.gnupg

**Comment by mrgravy20** [comment]
Thank you!
